services:
  - type: web
    name: ctfd
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:////data/ctfd.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
